steps:
  # Docker imajını kaynaktan inşa et (Etiket olarak commit ID'sini basıyoruz)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/storyapp:$COMMIT_SHA', '.']

  # Oluşan imajı Google Container Registry (GCR) deposuna güvenlice yükle
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storyapp:$COMMIT_SHA']

  # Google Kubernetes Engine (GKE) kümesine güvenli bağlantı kur
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'storyapp-cluster'
      - '--region'
      - 'europe-west3'

  # deployment.yaml içindeki imajı güncelleyip tüm k8s manifestlerini uygula
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|image:.*|image: gcr.io/$PROJECT_ID/storyapp:$COMMIT_SHA|g' k8s/deployment.yaml
        kubectl apply -f k8s/

images:
  - 'gcr.io/$PROJECT_ID/storyapp:$COMMIT_SHA'