apiVersion: v1
kind: Secret
metadata:
  name: storyapp-db-secret
  labels:
    project: storyapp-odev
type: Opaque
data:
  # MongoDB Atlas bağlantı linkimizin güvenli hali
  mongo-uri: bW9uZ29kYitzcnY6Ly9zZXltYV9kZXY6QXk1Mzk0MjBAY2x1c3RlcjAucnFoNW1kdi5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==