apiVersion: v1
kind: Secret
metadata:
  name: storyapp-db-secret
  labels:
    project: storyapp-odev
type: Opaque
data:
  # MongoDB Atlas bağlantı linkimizin güvenli hali
  mongo-uri: bW9uZ29kYitzcnY6Ly9zZXltYV9kZXY6bEw1WEJXbXdDdXN1OGpPd0BjbHVzdGVyMC5ycWg1bWR2Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw